# Generated by Django 4.2.2 on 2023-06-22 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosource',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 22, 21, 20, 11, 226426)),
        ),
        migrations.AlterField(
            model_name='photosource',
            name='gallery_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='photosource',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='season',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
