# Generated by Django 4.2.2 on 2023-06-23 16:48

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_photosource_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='photo',
            field=models.FileField(null=True, storage=storages.backends.s3boto3.S3Boto3Storage, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photosource',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
