# Generated by Django 4.2.2 on 2023-06-25 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_projects_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
