# Generated by Django 4.2.2 on 2023-06-25 21:41

from django.db import migrations, models
import storages.backends.s3boto3
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_projects_project_rename_tags_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photosource',
            old_name='project',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='photosource',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='photosource',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=website.models.get_photo_upload_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
